//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CsiProgram.EFModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CsiProgramManagementEntities : DbContext
    {
        public CsiProgramManagementEntities()
            : base("name=CsiProgramManagementEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<T_CSI_PROJECT> T_CSI_PROJECT { get; set; }
        public DbSet<T_CSI_PROJECT_DETAIL> T_CSI_PROJECT_DETAIL { get; set; }
        public DbSet<T_CSI_PROJECT_FILE> T_CSI_PROJECT_FILE { get; set; }
        public DbSet<T_CSI_PROJECT_MEMBER> T_CSI_PROJECT_MEMBER { get; set; }
        public DbSet<T_CSI_PROJECTCOST_DETAIL> T_CSI_PROJECTCOST_DETAIL { get; set; }
        public DbSet<T_CSI_TASK> T_CSI_TASK { get; set; }
        public DbSet<T_CSI_TASK_DETAIL> T_CSI_TASK_DETAIL { get; set; }
        public DbSet<T_CSI_TASK_MEMBER> T_CSI_TASK_MEMBER { get; set; }
        public DbSet<T_SYS_MENU> T_SYS_MENU { get; set; }
        public DbSet<T_SYS_ROLE> T_SYS_ROLE { get; set; }
        public DbSet<T_SYS_ROLE_MENU> T_SYS_ROLE_MENU { get; set; }
        public DbSet<T_SYS_USER> T_SYS_USER { get; set; }
        public DbSet<T_SYS_USER_ROLE> T_SYS_USER_ROLE { get; set; }
        public DbSet<T_BASE_STATUS> T_BASE_STATUS { get; set; }
    }
}
