//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CsiProgram.EFModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_CSI_PROJECT
    {
        public int ID { get; set; }
        public string PROJECT_NAME { get; set; }
        public string PROJECT_TYPE { get; set; }
        public string PROJECT_STATUS { get; set; }
        public string APPLY_USER { get; set; }
        public string ACCEPT_USER { get; set; }
        public string PLAN_STARTTIME { get; set; }
        public string PLAN_ENDTIME { get; set; }
        public string ACTUAL_STARTTIME { get; set; }
        public string ACTUAL_ENDTIME { get; set; }
        public string CREATED_ON { get; set; }
        public string CREATED_BY { get; set; }
    }
}
