//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CsiProgram.EFModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_CSI_PROJECT_FILE
    {
        public int ID { get; set; }
        public int PROJECT_ID { get; set; }
        public string FILE_NAME { get; set; }
        public string FILE_TYPE { get; set; }
        public string FILE_DESCRIPTION { get; set; }
        public string CREATED_ON { get; set; }
        public string CREATED_BY { get; set; }
        public string MODIFIED_ON { get; set; }
        public string MODIFIED_BY { get; set; }
    }
}
