//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CsiProgram.EFModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_CSI_PROJECTCOST_DETAIL
    {
        public int ID { get; set; }
        public int PROJECT_ID { get; set; }
        public string COST_NAME { get; set; }
        public Nullable<decimal> PRICE { get; set; }
        public Nullable<int> QUANTITY { get; set; }
        public string CURRENCY { get; set; }
        public string DESCRIPTION { get; set; }
    }
}
