//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CsiProgram.EFModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_CSI_TASK_MEMBER
    {
        public int ID { get; set; }
        public Nullable<int> TASK_ID { get; set; }
        public Nullable<int> MEMBER_ID { get; set; }
        public string MEMBER_NAME { get; set; }
        public string REMARK { get; set; }
    }
}
