//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CsiProgram.EFModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_CSI_PROJECT_DETAIL
    {
        public int ID { get; set; }
        public int PROJECT_ID { get; set; }
        public Nullable<decimal> PROJECT_PLANCOST { get; set; }
        public Nullable<decimal> PROJECT_ACTUALCOST { get; set; }
        public string BACKGROUND { get; set; }
        public string PLANWORKTIME { get; set; }
        public string DESCRIPTION { get; set; }
        public string RESV01 { get; set; }
        public string RESV02 { get; set; }
        public string RESV03 { get; set; }
        public string RESV04 { get; set; }
        public string RESV05 { get; set; }
    }
}
